services:
  db:
    container_name: my_postgres
    image: postgres:latest
    
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PGDATA: /data/postgres
    ports:
      - '5332:5432'
    networks:
      - backend
    volumes:
      - db:/data/postgres
    restart: unless-stopped
  redis:
    container_name: my_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - redis_data:/data
    restart: unless-stopped
networks:
  backend:
    driver: bridge

volumes:
  db:
  redis_data:
