spring:
  application:
    name: blog

  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MyHikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      auto-commit: true
      connection-init-sql: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[jdbc.time_zone]': UTC
        # dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes
      cache-null-values: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          timeoute: 5000
          connectiontimeout: 5000
  # email templates
  thymeleaf:
    suffix: .html
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration: ${JWT_REFRESH_EXPIRATION}

server:
  port: 7005
logging:
  level:
    root: INFO
    '[org.springframework.security.web.FilterChainProxy]': DEBUG
    '[com.johnson]': DEBUG
    # '[com.zaxxer.hikari]': DEBUG
